require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Core::ProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # Core::Project. As you add validations to Core::Project, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Core::ProjectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all core_projects as @core_projects" do
      project = Core::Project.create! valid_attributes
      get :index, {}, valid_session
      assigns(:core_projects).should eq([project])
    end
  end

  describe "GET show" do
    it "assigns the requested core_project as @core_project" do
      project = Core::Project.create! valid_attributes
      get :show, {:id => project.to_param}, valid_session
      assigns(:core_project).should eq(project)
    end
  end

  describe "GET new" do
    it "assigns a new core_project as @core_project" do
      get :new, {}, valid_session
      assigns(:core_project).should be_a_new(Core::Project)
    end
  end

  describe "GET edit" do
    it "assigns the requested core_project as @core_project" do
      project = Core::Project.create! valid_attributes
      get :edit, {:id => project.to_param}, valid_session
      assigns(:core_project).should eq(project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Core::Project" do
        expect {
          post :create, {:core_project => valid_attributes}, valid_session
        }.to change(Core::Project, :count).by(1)
      end

      it "assigns a newly created core_project as @core_project" do
        post :create, {:core_project => valid_attributes}, valid_session
        assigns(:core_project).should be_a(Core::Project)
        assigns(:core_project).should be_persisted
      end

      it "redirects to the created core_project" do
        post :create, {:core_project => valid_attributes}, valid_session
        response.should redirect_to(Core::Project.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved core_project as @core_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Project.any_instance.stub(:save).and_return(false)
        post :create, {:core_project => {}}, valid_session
        assigns(:core_project).should be_a_new(Core::Project)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Project.any_instance.stub(:save).and_return(false)
        post :create, {:core_project => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested core_project" do
        project = Core::Project.create! valid_attributes
        # Assuming there are no other core_projects in the database, this
        # specifies that the Core::Project created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Core::Project.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => project.to_param, :core_project => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested core_project as @core_project" do
        project = Core::Project.create! valid_attributes
        put :update, {:id => project.to_param, :core_project => valid_attributes}, valid_session
        assigns(:core_project).should eq(project)
      end

      it "redirects to the core_project" do
        project = Core::Project.create! valid_attributes
        put :update, {:id => project.to_param, :core_project => valid_attributes}, valid_session
        response.should redirect_to(project)
      end
    end

    describe "with invalid params" do
      it "assigns the core_project as @core_project" do
        project = Core::Project.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Project.any_instance.stub(:save).and_return(false)
        put :update, {:id => project.to_param, :core_project => {}}, valid_session
        assigns(:core_project).should eq(project)
      end

      it "re-renders the 'edit' template" do
        project = Core::Project.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Project.any_instance.stub(:save).and_return(false)
        put :update, {:id => project.to_param, :core_project => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested core_project" do
      project = Core::Project.create! valid_attributes
      expect {
        delete :destroy, {:id => project.to_param}, valid_session
      }.to change(Core::Project, :count).by(-1)
    end

    it "redirects to the core_projects list" do
      project = Core::Project.create! valid_attributes
      delete :destroy, {:id => project.to_param}, valid_session
      response.should redirect_to(core_projects_url)
    end
  end

end
