inherit_from: .rubocop_todo.yml
Style/AsciiComments:
  Enabled: false
Style/CaseIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
#  think about documentation
Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'lib/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'script/**/*'

