#inherit_from: .rubocop_todo.yml
Style/AsciiComments:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'lib/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'script/**/*'

