source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '4.1.6'

group :development, :test do
  gem 'quiet_assets'
  gem 'grizzled-rails-logger'
  gem 'rspec-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'faker'
  gem 'bullet'
end

group :development do
  gem 'spring'
  gem 'html2haml', '1.0.0'
  gem 'rubocop'
  gem 'ruby-prof'
  gem 'rspec-prof'
  gem 'brakeman', require: false
  gem 'rails_best_practices'
  gem 'guard-livereload'
  gem 'lol_dba'
  gem 'yard'
  gem 'rubycritic'
  gem 'traceroute'
end

group :production do
  gem 'rails_12factor'
  gem 'newrelic_rpm', '>=3.7.3'
  gem 'heroku-deflater'
end

group :test do
  gem 'rspec'
  gem 'spork'
  gem 'spork-rails'
  gem 'guard-spork'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'database_cleaner'
  gem 'selenium-webdriver', '~> 2.41.0'
  gem 'webdriver-user-agent'
  gem 'capybara-webkit'
  gem 'capybara-screenshot'
  gem 'headless'
  gem 'codeclimate-test-reporter', require: nil
end

gem 'foreman'
gem 'thin'
gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.1'
gem 'uglifier', '>= 2.1.1'
gem 'compass'
gem 'compass-rails'
gem 'therubyracer', '>=0.11.4'
gem 'websocket-rails', git: 'https://github.com/samhane/websocket-rails.git'
gem 'cloudinary'
gem 'remotipart', '~> 1.2'
gem 'pg'
gem 'activerecord-postgresql-adapter'
gem 'russian'
gem 'bootstrap-x-editable-rails'
gem 'selectize-rails'
gem 'rails3-jquery-autocomplete', '1.0.14'
gem 'devise'
gem 'haml'
gem 'haml-rails'
gem 'jquery-rails'
gem 'jquery-ui-sass-rails'
gem 'paperclip'
gem 'aws-sdk'
gem 'autosize-rails'
gem 'highcharts-rails', '~> 3.0.0'
gem 'json'
gem 'will_paginate', '~> 3.0.0'
gem 'devise_lastseenable'
gem 'memcachier'
gem 'dalli'
gem 'settingslogic'
gem 'bootstrap-wysihtml5-rails'
gem 'rest-client'
gem 'magic_encoding'
gem 'similar_text'
gem 'breadcrumbs_on_rails'
gem 'tinymce-rails'
gem 'historyjs-rails'
gem 'seed_migration'

gem 'resque'
gem 'resque_mailer'
gem 'resque-scheduler'
gem 'resque-status'
gem 'rufus-scheduler', '< 3.0.0'
