# config/application.yml
defaults: &defaults
# количество неудовлетворенностей на 1 человека
  max_frustration: 3
  current_stage: 'concept'
# дней для принятия неструктурированной
  days_accept_unstracture: 3
# дней лежит в архиве неструктурированная
  days_archive_unstracure: 5
# дней для принятия структурированной 
  days_accept_stracture: 3
# баллы
  scores:
    unstructure:
      violation_comment: -5
      abuse_comment: -20
      violation_frustration: -10
      abuse_frustration: -20
      denial_for_negative_comment: 10
    structure:
      violation_comment: -5
      abuse_comment: -20
      violation_frustration: -10
      abuse_frustration: -20
      denial_for_negative_comment: 10
    expert:
      allow: 50
      ratio_for_structuring_comment: 0.4
      ratio_for_negative_comment: 0.2
      allow_with_replacement: 100
      deny_with_negative: -50






development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults