# config/application.yml
defaults: &defaults
# количество неудовлетворенностей на 1 человека
  max_frustration: 3
# дней для принятия неструктурированной
  days_accept_unstracture: 1
# дней лежит в архиве неструктурированная
  days_archive_unstracure: 5
# дней для принятия структурированной 
  days_accept_stracture: 3
# баллы
  scores:
    unstructure:
      violation_comment: -1
      abuse_comment: -10
      violation_frustration: -10
      abuse_frustration: -20
      denial_for_negative_comment: 10
    structure:
      violation_comment: -1
      abuse_comment: -10
      violation_frustration: -10
      abuse_frustration: -20
      denial_for_negative_comment: 10





development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults