every_hour_from_10_to_24_hours:
  #  every: "1d"
  cron: "0 10-24/4 * * *"
  class: FeedModeratorMailer
  queue: feed_moderator_mailer
  args:
  description: "This job..."

every_day_at_20_hours:
  #  every: "1d"
  cron: "0 20 * * *"
  class: FeedUserMailer
  queue: feed_user_mailer
  args:
  description: "This job..."

every_minute_puts_time_in_console:
  #  every: "1d"
  cron: "0-59 * * * *"
  class: LogTask
  queue: log_proc
  args:
  description: "This job..."
