theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_simple_toolbar_location: top
theme_simple_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1: "bold,italic,underline,separator,forecolor,backcolor"
theme_advanced_buttons2: "bullist,numlist,separator,outdent,indent,separator,undo,redo,separator,link,unlink, image"
theme_advanced_buttons3: ""

plugins:
  - table
  - fullscreen